#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/420eca02-64a9-4dc5-a563-b6ab9edd04ba 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudSwitch cocina;
  CloudSwitch cuarto;
  CloudSwitch pasillo;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
*/

#include "thingProperties.h"

const int Switch1 = 23; // Para el cuarto
const int Switch2 = 22; // Para la cocina
const int Switch3 = 21; // Para el pasillo
const int Switch4 = 19; // (Se puede usar para otro dispositivo o dejarlo vacío)

void setup() {
  // Inicializa la comunicación serial
  Serial.begin(9600);
  delay(1500);

  pinMode(Switch1, OUTPUT);
  pinMode(Switch2, OUTPUT);
  pinMode(Switch3, OUTPUT);
  pinMode(Switch4, OUTPUT);

  // Inicializa las propiedades de Arduino Cloud
  initProperties();

  // Conecta con Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
}

/*
  Since cuarto is READ_WRITE variable, onCuartoChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCuartoChange() {
  if (cuarto) {
    digitalWrite(Switch1, HIGH);
    Serial.println("Cuarto ON");
  } else {
    digitalWrite(Switch1, LOW);
    Serial.println("Cuarto OFF");
  }
}

/*
  Since cocina is READ_WRITE variable, onCocinaChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCocinaChange() {
  if (cocina) {
    digitalWrite(Switch2, HIGH);
    Serial.println("Cocina ON");
  } else {
    digitalWrite(Switch2, LOW);
    Serial.println("Cocina OFF");
  }
}

/*
  Since pasillo is READ_WRITE variable, onPasilloChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onPasilloChange() {
  if (pasillo) {
    digitalWrite(Switch3, HIGH);
    Serial.println("Pasillo ON");
  } else {
    digitalWrite(Switch3, LOW);
    Serial.println("Pasillo OFF");
  }
}